name: cabi_net
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python==3.7
  - pip:
    - setuptools_scm>=6.4.2,<8.0.0
    - pyparsing==2.4.7
    - pytorch-lightning==1.8.3
    - scipy==1.4.1
    - https://download.pytorch.org/whl/cu111/torch-1.9.0%2Bcu111-cp37-cp37m-linux_x86_64.whl 
    - https://data.pyg.org/whl/torch-1.9.0+cu111/torch_scatter-2.0.7-cp37-cp37m-linux_x86_64.whl
    - torchvision==0.10.0
    - torchaudio==0.9.0
    - torchmetrics==0.9.3
    - trimesh==3.12.0
    - meshcat==0.3.2
    - networkx==2.2
    - urdfpy==0.0.22
    - yourdfpy==0.0.46
    - pyglet==1.5.21
    - seaborn==0.11.2
    - matplotlib==3.5.1
    - open3d==0.14.1
    - h5py==3.8.0
    - autolab-core==1.1.0
    - yacs==0.1.8